version: '3.9'
services:

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 10s
      timeout: 5s
      retries: 5

  empmanage:
    container_name: empmanage1
    build:
      context: ..
      dockerfile: Dockerfile
    image: empmanage
    ports:
      - 8082:8080
    environment:
      TZ: Europe/Moscow

    depends_on:
      - postgres