CREATE TABLE SOAP.EMPLOYEES
(
    ID        BIGINT NOT NULL,
    FIRSTNAME VARCHAR(32),
    LASTNAME  VARCHAR(32),
    AGE       INTEGER,
    POSITION  VARCHAR(16),
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX EMPLOYEES_ID_INDX ON SOAP.EMPLOYEES (ID);