CREATE TABLE SOAP.EMPLOYEES
(
    ID        BIGINT NOT NULL,
    FIRST_NAME VARCHAR(32),
    LAST_NAME  VARCHAR(32),
    AGE       INTEGER,
    SALARY       INTEGER,
    LEVEL       VARCHAR(16),
    LANGUAGE       VARCHAR(16),
    TYPE       VARCHAR(16),
    PROJECT VARCHAR(16),
    UUID        VARCHAR(40),
    POSITION  VARCHAR(16),
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX EMPLOYEES_ID_INDX ON SOAP.EMPLOYEES (ID);
CREATE UNIQUE INDEX EMPLOYEES_UUID ON SOAP.EMPLOYEES (UUID);