CREATE TABLE SOAP.TASKS
(
    ID        VARCHAR(32) NOT NULL,
    EMPLOYEE_ID BIGINT NOT NULL,
    DESCRIPTION  VARCHAR(128),
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX TASKS_ID_INDX ON SOAP.TASKS (ID);